### ISSUE TITLE
ChuwiBiosLogo.zip

### ISSUE THREAD

**Issue by Annncao** [weachy/CoreBookX-14-Hackintosh#15]
Thanks for great work.

1. Please tell me where to download ChuwiBiosLogo.zip?

2. Can you send me a photo of Broadcom BCM94360CS2, which you placed Intel 7265 with since it is non-removable WLAN module

**Comment by weachy** [comment]
1.
Someone flashed my bios zip and couldn't boot up. I guess it is caused by different bios versions. Before I confirm the reason, I suggest using UEFI Tool to change bios logo by myself.
2.
![Corebook_with_BCM94360cs2](https://user-images.githubusercontent.com/8164171/145524924-3d3e769f-55ba-496e-8bc3-6eecff360e07.JPG)

**Comment by bricamac** [comment]
May you explain how you have change wifi chip on chuwi corebook ?  do you need to unsolder the existing wifi chip ?
Because sadly my chuwi have realtek chipset :-( At present time I have to use an usb wifi key :-( to get wifi on my latop)

Thanks again for your help.

**Comment by Annncao** [comment]
Are you using kind of this one @weachy 
![Uploading 5B828BCC-D0E0-48F7-AA2E-420B7AF88778.jpeg…]()

**Comment by Annncao** [comment]
![Uploading 37E84D87-802E-4097-AD87-E51458FBE153.jpeg…]()

**Comment by weachy** [comment]
> 

Yes, unsolder. And we designed a PCB to plug Broadcom WiFi/Bluetooth Card from Mac.
